server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter ğŸ‰ğŸ‰
            preLogger: true
            postLogger: true
      routes:
        # member - ë¡œê·¸ì¸ í•„ìš” X
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/api/member/check
          filters:
            - CustomFilter
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/api/member/join
          filters:
            - CustomFilter
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/api/member/login
          filters:
            - CustomFilter
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/actuator/**
          filters:
            - CustomFilter
            - RewritePath=/member/(?<segment>.*), /$\{segment}
        # member - ë¡œê·¸ì¸ í•„ìš”
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/api/member/**
          filters:
            - CustomFilter
            - AuthorizationHeaderFilter

        # chat - ë¡œê·¸ì¸ í•„ìš” X
        - id: chat
          uri: lb://CHAT
          predicates:
            - Path=/chat/actuator/**
          filters:
            - CustomFilter
            - RewritePath=/chat/(?<segment>.*), /$\{segment}
        - id: chat
          uri: lb://CHAT
          predicates:
            - Path=/api/chat/check
          filters:
            - CustomFilter
        # chat - ë¡œê·¸ì¸ í•„ìš”
        - id: chat
          uri: lb://CHAT
          predicates:
            - Path=/api/chat/**
          filters:
            - CustomFilter
            - AuthorizationHeaderFilter

        # item - ë¡œê·¸ì¸ í•„ìš”
        - id: item
          uri: lb://ITEM
          predicates:
            - Path=/api/item/like
          filters:
            - CustomFilter
            - AuthorizationHeaderFilter
        # item - ë¡œê·¸ì¸ í•„ìš” x
        - id: item
          uri: lb://ITEM
          predicates:
            - Path=/api/item/**
          filters:
            - CustomFilter
        - id: item
          uri: lb://ITEM
          predicates:
            - Path=/item/actuator/**
          filters:
            - CustomFilter
            - RewritePath=/item/(?<segment>.*), /$\{segment}

        # flight - ë¡œê·¸ì¸ í•„ìš”
        - id: flight
          uri: lb://FLIGHT
          predicates:
            - Path=/api/flight/one/like
          filters:
            - CustomFilter
            - AuthorizationHeaderFilter
        - id: flight
          uri: lb://FLIGHT
          predicates:
            - Path=/api/flight/round/like
          filters:
            - CustomFilter
            - AuthorizationHeaderFilter
        # flight - ë¡œê·¸ì¸ X
        - id: flight
          uri: lb://FLIGHT
          predicates:
            - Path=/api/flight/**
          filters:
            - CustomFilter
        - id: flight
          uri: lb://FLIGHT
          predicates:
            - Path=/flight/actuator/**
          filters:
            - CustomFilter
            - RewritePath=/flight/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"

token:
  secret: "pickpack"

logging:
  config: classpath:Logback-spring.xml